# Generated by Django 4.0 on 2024-03-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patient',
        ),
    ]
