# Generated by Django 4.0 on 2024-03-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_patient_heartrate_alter_patient_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
