# Generated by Django 4.0 on 2024-03-29 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_teacker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teacker',
            new_name='teacher',
        ),
    ]
